<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.v.HUAWx' shared service.

return $this->privates['.service_locator.v.HUAWx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService.php', true],
], [
    'projectRepository' => 'App\\Repository\\ProjectRepository',
]);
