<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mzNMQQM' shared service.

return $this->privates['.service_locator.mzNMQQM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'issue' => ['privates', '.errored..service_locator.mzNMQQM.App\\Entity\\Issue', NULL, 'Cannot autowire service ".service_locator.mzNMQQM": it references class "App\\Entity\\Issue" but no such service exists.'],
    'project' => ['privates', '.errored..service_locator.mzNMQQM.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.mzNMQQM": it references class "App\\Entity\\Project" but no such service exists.'],
], [
    'issue' => 'App\\Entity\\Issue',
    'project' => 'App\\Entity\\Project',
]);
