<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wYcM4Tb' shared service.

return $this->privates['.service_locator.wYcM4Tb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\IssueController::delete' => ['privates', '.service_locator.R2Av0TT', 'get_ServiceLocator_R2Av0TTService.php', true],
    'App\\Controller\\IssueController::edit' => ['privates', '.service_locator.R2Av0TT', 'get_ServiceLocator_R2Av0TTService.php', true],
    'App\\Controller\\IssueController::new' => ['privates', '.service_locator.8SSwaBs', 'get_ServiceLocator_8SSwaBsService.php', true],
    'App\\Controller\\IssueController::show' => ['privates', '.service_locator.R2Av0TT', 'get_ServiceLocator_R2Av0TTService.php', true],
    'App\\Controller\\ProjectController::delete' => ['privates', '.service_locator.8SSwaBs', 'get_ServiceLocator_8SSwaBsService.php', true],
    'App\\Controller\\ProjectController::edit' => ['privates', '.service_locator.8SSwaBs', 'get_ServiceLocator_8SSwaBsService.php', true],
    'App\\Controller\\ProjectController::index' => ['privates', '.service_locator.v.HUAWx', 'get_ServiceLocator_V_HUAWxService.php', true],
    'App\\Controller\\ProjectController::show' => ['privates', '.service_locator.8SSwaBs', 'get_ServiceLocator_8SSwaBsService.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\IssueController:delete' => ['privates', '.service_locator.R2Av0TT', 'get_ServiceLocator_R2Av0TTService.php', true],
    'App\\Controller\\IssueController:edit' => ['privates', '.service_locator.R2Av0TT', 'get_ServiceLocator_R2Av0TTService.php', true],
    'App\\Controller\\IssueController:new' => ['privates', '.service_locator.8SSwaBs', 'get_ServiceLocator_8SSwaBsService.php', true],
    'App\\Controller\\IssueController:show' => ['privates', '.service_locator.R2Av0TT', 'get_ServiceLocator_R2Av0TTService.php', true],
    'App\\Controller\\ProjectController:delete' => ['privates', '.service_locator.8SSwaBs', 'get_ServiceLocator_8SSwaBsService.php', true],
    'App\\Controller\\ProjectController:edit' => ['privates', '.service_locator.8SSwaBs', 'get_ServiceLocator_8SSwaBsService.php', true],
    'App\\Controller\\ProjectController:index' => ['privates', '.service_locator.v.HUAWx', 'get_ServiceLocator_V_HUAWxService.php', true],
    'App\\Controller\\ProjectController:show' => ['privates', '.service_locator.8SSwaBs', 'get_ServiceLocator_8SSwaBsService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\IssueController::delete' => '?',
    'App\\Controller\\IssueController::edit' => '?',
    'App\\Controller\\IssueController::new' => '?',
    'App\\Controller\\IssueController::show' => '?',
    'App\\Controller\\ProjectController::delete' => '?',
    'App\\Controller\\ProjectController::edit' => '?',
    'App\\Controller\\ProjectController::index' => '?',
    'App\\Controller\\ProjectController::show' => '?',
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\IssueController:delete' => '?',
    'App\\Controller\\IssueController:edit' => '?',
    'App\\Controller\\IssueController:new' => '?',
    'App\\Controller\\IssueController:show' => '?',
    'App\\Controller\\ProjectController:delete' => '?',
    'App\\Controller\\ProjectController:edit' => '?',
    'App\\Controller\\ProjectController:index' => '?',
    'App\\Controller\\ProjectController:show' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
