<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.R2Av0TT' shared service.

return $this->privates['.service_locator.R2Av0TT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'issue' => ['privates', '.errored..service_locator.R2Av0TT.App\\Entity\\Issue', NULL, 'Cannot autowire service ".service_locator.R2Av0TT": it references class "App\\Entity\\Issue" but no such service exists.'],
], [
    'issue' => 'App\\Entity\\Issue',
]);
