<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHUlc3hn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHUlc3hn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHUlc3hn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHUlc3hn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHUlc3hn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HUlc3hn',
    'container.build_id' => 'ab45adfa',
    'container.build_time' => 1563381301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHUlc3hn');
